name: Publish

on:
  push:
    tags:
      - '*.*.*'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: publish
        env:
          NUGET_URL: https://api.nuget.org/v3/index.json
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: ./publish.ps1
        shell: pwsh
